name: taskManager-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: make setup

    - name: Run linter
      run: make lint

    - name: Run Feature tests
      run: make test-coverage

    - name: install Uploader Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t CODECOV_TOKEN
